version: "3"
services:
  typedoc-api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "3000:3000"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
